// Finnish words for the typing game
// Common Finnish words of varying difficulty
const FINNISH_WORDS = [
    'kissa', 'koira', 'talo', 'kirja', 'puu', 'vettä', 'aurinko', 'kuu',
    'ihminen', 'auto', 'tietokone', 'matkapuhelin', 'ikkuna', 'ovi', 'lattia',
    'taivas', 'maa', 'meri', 'joki', 'järvi', 'metsä', 'kukka', 'ruoho',
    'lehti', 'hedelmä', 'vihannes', 'leipä', 'maito', 'kahvi', 'tee', 'vesi',
    'ruoka', 'ateria', 'aamupala', 'lounas', 'päivällinen', 'illallinen',
    'perhe', 'isä', 'äiti', 'sisko', 'veli', 'isovanhemmat', 'yö', 'päivä',
    'aamu', 'iltapäivä', 'ilta', 'viikko', 'kuukausi', 'vuosi', 'tunti',
    'minuutti', 'sekunti', 'maanantai', 'tiistai', 'keskiviikko', 'torstai',
    'perjantai', 'lauantai', 'sunnuntai', 'tammikuu', 'helmikuu', 'maaliskuu',
    'huhtikuu', 'toukokuu', 'kesäkuu', 'heinäkuu', 'elokuu', 'syyskuu',
    'lokakuu', 'marraskuu', 'joulukuu', 'koulu', 'opettaja', 'oppilas',
    'luokka', 'työ', 'työntekijä', 'pomo', 'toimisto', 'työpaikka',
    'ystävä', 'kaveri', 'naapuri', 'kaupunki', 'kylä', 'katu', 'tie',
    'silta', 'rakennus', 'asunto', 'huone', 'keittiö', 'makuuhuone',
    'olohuone', 'kylpyhuone', 'ikkuna', 'parveke', 'piha', 'puutarha',
    'kirjasto', 'kirjasto', 'museo', 'teatteri', 'elokuvateatteri', 'ravintola',
    'kahvila', 'kauppa', 'ruokakauppa', 'apteekki', 'sairaala', 'poliisi',
    'palokunta', 'säätiedotus', 'sää', 'aurinkoinen', 'pilvinen', 'sateinen',
    'lumi', 'sade', 'tuuli', 'pakkanen', 'lämpötila', 'kuuma', 'kylmä',
    'lämmin', 'viileä', 'värjätty', 'punainen', 'sininen', 'vihreä',
    'keltainen', 'oranssi', 'violetti', 'musta', 'valkoinen', 'harmaa',
    'ruskea', 'vaaleanpunainen', 'iso', 'pieni', 'pitkä', 'lyhyt', 'leveä',
    'kapea', 'korkea', 'matala', 'raskas', 'kevyt', 'nopea', 'hidas',
    'hyvä', 'huono', 'kaunis', 'ruma', 'nuori', 'vanha', 'uusi', 'vanha',
    'puhdas', 'likainen', 'helppo', 'vaikea', 'oikea', 'väärä', 'tosi',
    'väärä', 'yksinkertainen', 'monimutkainen', 'tyhjä', 'täynnä', 'kiireinen',
    'vapaa', 'onnellinen', 'surullinen', 'vihainen', 'pelokas', 'rohkea',
    'iloinen', 'ärsyyntynyt', 'rauhallinen', 'levoton', 'väsynyt', 'energinen',
    'nälkäinen', 'janoinen', 'terve', 'sairas', 'voimakas', 'heikko',
    'rikas', 'köyhä', 'viisas', 'tyhmä', 'ystävällinen', 'epäystävällinen',
    'kärsivällinen', 'kärsimätön', 'rehellinen', 'epärehellinen', 'laiska',
    'ahkera', 'hiljainen', 'meluisa', 'pehmeä', 'kova', 'sileä', 'karhea',
    'makea', 'hapan', 'suolainen', 'karhea', 'maukas', 'mauton', 'tuore',
    'vanhentunut', 'kiireinen', 'rauhallinen', 'turvallinen', 'vaarallinen',
    'lähellä', 'kaukana', 'vasen', 'oikea', 'ylhäällä', 'alhaalla',
    'edessä', 'takana', 'vieressä', 'keskellä', 'sisällä', 'ulkona',
    'yläpuolella', 'alapuolella', 'sisään', 'ulos', 'ylös', 'alas',
    'eteenpäin', 'taaksepäin', 'ympäri', 'läpi', 'poikki', 'vieressä',
    'vastapäätä', 'viereen', 'lähelle', 'kauas', 'pitkin', 'poikki',
    'lähden', 'tulen', 'menen', 'olen', 'tulen', 'saavun', 'poistun',
    'pysähdyn', 'kiirehdin', 'kiipeän', 'hyppään', 'juoksen', 'kävelen',
    'liu\'un', 'ui', 'lennän', 'ajelen', 'pyöräilen', 'matkustan',
    'tulen', 'menen', 'lähetän', 'vastaanotan', 'annat', 'otat', 'antaa',
    'ottaa', 'tehdä', 'valmistaa', 'rakentaa', 'rikkoa', 'korjata',
    'avata', 'sulkea', 'panna', 'ottaa pois', 'nostaa', 'laskea',
    'työntää', 'vetää', 'lyödä', 'potkia', 'heittää', 'ottaa kiinni',
    'pitää kiinni', 'päästää irti', 'puristaa', 'koskea', 'raapia',
    'hieroa', 'pusertaa', 'vetää', 'työntää', 'kiertää', 'kääntää',
    'liikkua', 'pysähtyä', 'seisoa', 'istua', 'maata', 'nukkua',
    'herätä', 'nousta', 'mennä nukkumaan', 'levätä', 'rentoutua',
    'työskennellä', 'leikkiä', 'opiskella', 'lukea', 'kirjoittaa',
    'piirtää', 'maalata', 'soittaa', 'laulaa', 'tanssia', 'kuunnella',
    'katsoa', 'nähdä', 'kuulla', 'hajota', 'haistaa', 'maistaa',
    'koskettaa', 'tuntea', 'ajatella', 'miettiä', 'muistaa', 'unohtaa',
    'ymmärtää', 'oppia', 'opettaa', 'selittää', 'kertoa', 'kuulla',
    'kysyä', 'vastata', 'puhua', 'keskustella', 'huutaa', 'kuiskata',
    'nauraa', 'itkeä', 'hymyillä', 'näyttää surulliselta', 'pelätä',
    'pelottaa', 'yllättyä', 'hämmästyä', 'vihata', 'rakastaa', 'tykätä',
    'pitää', 'ei pidä', 'haluta', 'tarvita', 'saada', 'antaa', 'ottaa',
    'myydä', 'ostaa', 'maksaa', 'säästää', 'lainata', 'palauttaa',
    'löytää', 'kadota', 'etsiä', 'löytää', 'löytää', 'kadota', 'nähdä',
    'näyttää', 'piilottaa', 'paljastaa', 'avata', 'sulkea', 'panna kiinni',
    'kirjoittaa', 'lukea', 'kuunnella', 'puhua', 'kertoa', 'selittää',
    'opettaa', 'oppia', 'ymmärtää', 'muistaa', 'unohtaa', 'ajatella',
    'miettiä', 'tietää', 'tietää', 'epäillä', 'uskoa', 'todistaa',
    'näyttää', 'tuntua', 'näyttää', 'kuulostaa', 'maistua', 'hajota',
    'haistaa', 'koskettaa', 'tuntea', 'kokea', 'tuntea', 'tuntea',
    'rakastaa', 'vihata', 'tykätä', 'ei pidä', 'haluta', 'tarvita',
    'saada', 'antaa', 'ottaa', 'pitää', 'pudottaa', 'heittää', 'ottaa kiinni',
    'puskea', 'vetää', 'työntää', 'nostaa', 'laskea', 'nostaa ylös',
    'panna alas', 'siirtää', 'siirtyä', 'kuljettaa', 'kantaa', 'tuoda',
    'viedä', 'lähettää', 'vastaanottaa', 'antaa', 'ottaa', 'jakaa',
    'kerätä', 'kerätä', 'kerätä', 'panna yhteen', 'erottaa', 'jakaa',
    'yhdistää', 'erottaa', 'kiinnittää', 'irrottaa', 'kytkeä', 'sammuttaa',
    'avata', 'sulkea', 'panna kiinni', 'purkaa', 'koota', 'rakentaa',
    'rikkoa', 'rikkoa', 'rikkoa', 'korjata', 'korjata', 'korjata',
    'tehdä', 'valmistaa', 'tuottaa', 'rakentaa', 'luoda', 'luoda',
    'aloittaa', 'lopettaa', 'jatkaa', 'pysähtyä', 'keskeyttää', 'valmistua',
    'alkaa', 'päättyä', 'jatkua', 'kestää', 'kestää', 'tapahtua',
    'tapahtua', 'sattua', 'tapahtua', 'tapahtua', 'muuttua', 'muuttua',
    'muuttua', 'kasvaa', 'pienentyä', 'lisätä', 'vähentää', 'kasvaa',
    'vähentyä', 'muuttua', 'muuttua', 'muuttua', 'muuttua', 'muuttua',
    'nousta', 'laskea', 'nousta', 'laskea', 'nousta', 'laskea',
    'kiivetä', 'laskeutua', 'nousta', 'laskeutua', 'nousta', 'laskeutua',
    'kiivetä', 'laskeutua', 'kiivetä', 'laskeutua', 'kiivetä', 'laskeutua',
    'nousta', 'laskea', 'nousta', 'laskea', 'nousta', 'laskea',
    'tulla', 'mennä', 'saapua', 'lähteä', 'poistua', 'palata', 'tulla takaisin',
    'lähteä', 'mennä', 'tulla', 'saapua', 'jäädä', 'pysyä', 'odottaa',
    'odottaa', 'odottaa', 'odottaa', 'seurata', 'ohittaa', 'ylittää',
    'päästä ohi', 'päästä yli', 'päästä läpi', 'päästä ulos', 'päästä sisään',
    'tulla ulos', 'tulla sisään', 'mennä ulos', 'mennä sisään', 'tulla',
    'mennä', 'kiirehtiä', 'hitaasti', 'nopeasti', 'hiljalleen', 'nopeasti',
    'heti', 'välittömästi', 'pian', 'myöhemmin', 'ennen', 'jälkeen',
    'nyt', 'sitten', 'tänään', 'huomenna', 'eilen', 'ylihuomenna',
    'toissa päivänä', 'viime viikolla', 'ensi viikolla', 'tällä viikolla',
    'viime kuussa', 'ensi kuussa', 'tässä kuussa', 'viime vuonna',
    'ensi vuonna', 'tänä vuonna', 'aamulla', 'iltapäivällä', 'illalla',
    'yöllä', 'päivällä', 'heti', 'välittömästi', 'pian', 'myöhemmin',
    'ennen', 'jälkeen', 'samaan aikaan', 'samanaikaisesti', 'yhdessä',
    'erikseen', 'itsenäisesti', 'yhdessä', 'yksin', 'yhdessä', 'erikseen',
    'yhdessä', 'erikseen', 'yhdessä', 'erikseen', 'yhdessä', 'erikseen',
    'aamulla', 'iltapäivällä', 'illalla', 'yöllä', 'päivällä', 'heti',
    'välittömästi', 'pian', 'myöhemmin', 'ennen', 'jälkeen', 'nyt',
    'sitten', 'tänään', 'huomenna', 'eilen', 'ylihuomenna', 'toissa päivänä',
    'viime viikolla', 'ensi viikolla', 'tällä viikolla', 'viime kuussa',
    'ensi kuussa', 'tässä kuussa', 'viime vuonna', 'ensi vuonna', 'tänä vuonna',
    'aamulla', 'iltapäivällä', 'illalla', 'yöllä', 'päivällä', 'heti',
    'välittömästi', 'pian', 'myöhemmin', 'ennen', 'jälkeen', 'nyt',
    'sitten', 'tänään', 'huomenna', 'eilen', 'ylihuomenna', 'toissa päivänä',
];

// Shuffle array function
function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

// Get random words for the game
function getRandomWords(count = 100) {
    const shuffled = shuffleArray(FINNISH_WORDS);
    return shuffled.slice(0, count);
}
